### ISSUE TITLE
Other augmentation methods for images

### ISSUE THREAD

**Issue by adavoudi** [google-research/uda#21]
I have a couple of questions regarding the augmentation method for images.

1. Have you tried other augmentation tools such as [imgaug](https://github.com/aleju/imgaug)? If not, do you think it'll work?

2. Is it a good idea to use pictures of the same object which are taken from different viewpoints as an alternative for the augmentation? 

Thank you in advance

**Comment by qizhex** [comment]
Hi!
1. No, I haven't tried imgaug. I think it will work as long as this augmentation works for supervised learning. 
2. Using pictures taken from different viewpoints are kind of similar to cropping where part of the object / image is hidden. I think it will lead to improvements but I am not sure if the improvement will be as large as using augmentation since augmentation might be able to generate more diverse images. You can first try it in the supervised learning. If it works, then it will likely to work in semi-supervised learning.

**Comment by adavoudi** [comment]
Thank you so much. I'll give it a try.
