### ISSUE TITLE
Question about "3.3 Domain-relevance Data Filtering"

### ISSUE THREAD

**Issue by varunnair18** [google-research/uda#27]
Hello,

In your paper, you state that you used out-of-domain data as such:

"We use our baseline model trained on the in-domain data to infer the labels of data in a large out of-domain dataset and pick out the examples (equally distributed among classes) that the model is most confident about."

What did you mean by picking out examples that are equally distributed among classes? My guess is that you created an unlabeled set from the JFT dataset of 1.3M images that were "class-balanced" according to the predictions by the baseline model?

**Comment by varunnair18** [comment]
Another question I have is, why was KL-divergence chosen as the method to enforce consistency training?

In other semi-supervised literature like MixMatch and ICT, consistency is enforced on the unlabeled data by encouraging the predicted distribution to be similar to that of a target distribution, where the targets are the sharpened predictions on augmented data.

The author of MixMatch claims that using MSE loss made the classifier more robust to incorrect targets (stated here: https://github.com/google-research/mixmatch/issues/7), did you attempt this approach as well or make any findings that don't support that?

**Comment by qizhex** [comment]
Hi,

> My guess is that you created an unlabeled set from the JFT dataset of 1.3M images that were "class-balanced" according to the predictions by the baseline model?

Yes. 

> KL loss vs MSE loss

In general, both KL divergence and MSE work well and have been widely used in semi-supervised learning methods. We followed the previous SOTA model VAT and used KL divergence. 

We haven't tried to use MSE on UDA. I guess the training signal of KL is indeed much stronger than the MSE objective, since all supervised training uses KL instead of MSE. Stronger training signal coming from KL divergence makes the training much faster. (If I remember correctly, MixMatch is trained for more than 1M steps while UDA is only trained for 400k steps.) As such, maybe using MSE might be similar to using KL divergence with a small weight on the unlabeled data loss. With a smaller weight, the model is also more robust to incorrect targets with the cost of longer training time.

**Comment by varunnair18** [comment]
I see, thanks for that information!

**Comment by abaheti95** [comment]
> baseline model trained on the in-domain data

Is this baseline model trained on sampled in-domain data (for example 20 examples from IMDB dataset) or the entire in-domain data (all of the IMDB dataset).
