### ISSUE TITLE
Offline vs Online Augmentation

### ISSUE THREAD

**Issue by sud0301** [google-research/uda#28]
I am trying to write my own implementation for CIFAR-10 (4k). But, I do not get similar performance. I still get Error more than 10%.  
How much difference does offline augmentation make as compared to online augmentation?

**Comment by qizhex** [comment]
Online augmentation should not be a problem. Offline augmentation is only used to save the training time and online augmentation should lead to better results since, if you use online augmentation, then the model sees different data at each iteration while the model can see the same data at different iterations with offline augmentation.
